### ISSUE TITLE
Crash on fetching weather data

### ISSUE THREAD

**Issue by omerakgoz34** [woheller69/weather#23]
**Describe the bug**
Crash on fetching weather data

**How to Reproduce**
it's random :/
3 times in 15 days

**Error: (catched with scoop app)**
```
FATAL EXCEPTION: main
Process: org.woheller69.weather, PID: 27389
java.lang.IndexOutOfBoundsException: Index: 47, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at org.woheller69.weather.weather_api.open_weather_map.ProcessOwmForecastRequest.processSuccessScenario(ProcessOwmForecastRequest.java:110)
	at org.woheller69.weather.http.VolleyHttpRequest$1.onResponse(VolleyHttpRequest.java:82)
	at org.woheller69.weather.http.VolleyHttpRequest$1.onResponse(VolleyHttpRequest.java:79)
	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6565)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Environment:**
 - App version: v3.2 F-droid
 - Android version: 8.0
 - Device: GM 5 Plus (codename=shamrock)[android-one]

**Comment by woheller69** [comment]
Fixed in V3.4
